.github/workflows/lint.yaml: add pre-commit check job
Signed-off-by: Adrian-Stanea <Adrian.Stanea@analog.com>

diff --git a/.github/workflows/lint.yaml b/.github/workflows/lint.yaml
--- a/.github/workflows/lint.yaml
+++ b/.github/workflows/lint.yaml
@@ -41,3 +41,25 @@ jobs:
           linter: ${{ matrix.linter }}
           distribution: ${{ matrix.ROS_DISTRIBUTION }}
           package-name: ${{ env.PACKAGE_NAME }}
+
+  pre_commit:
+    runs-on: ubuntu-22.04
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Setup ROS environment
+        uses: ros-tooling/setup-ros@v0.7
+
+      - name: Run pre-commit-checks
+        run: |
+          make fix
+          FIX_STATUS=$?
+
+          make check
+          CHECK_STATUS=$?
+
+          if [ $FIX_STATUS -ne 0 ] || [ $CHECK_STATUS -ne 0 ]; then
+            echo "Pre-commit checks failed. Please fix the issues and try again."
+            exit 1
+          fi
